[package]
name = "lildb-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "lildb_client"
path = "src/lib.rs"

[dependencies]
lildb-api = { path = "../api" }
log = { workspace = true }
