
[alias]
run-server = "run --package lildb-server --bin lildb-server"
run-cli = "run --package lildb-cli --bin lildb-cli"

[profile.dev]

[profile.release]

[profile.test]
inherits = "dev"

[profile.bench]
inherits = "release"