[package]
name = "lildb-ql"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
path="src/lib.rs"

[[bin]]
name="test-main"
path="src/lib.rs"

[dependencies]
lildb-api = { path = "../api" }