[package]
name = "lildb-api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "lildb_api"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
fastrand = "2.3.0"
